[workspace]

members = [
    "autd3-timer",
    "autd3-traits",
    "autd3-core",
    "autd3",
    "autd3-soem-link",
    "autd3-twincat-link",
    "autd3-emulator-link",
    "autd3-examples",
    "autd3-holo-gain"
]
