name: 'Cargo Publish All Action'
inputs:
  crate-io-token:
    description: 'Crate IO Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.crate-io-token }}
  