name: Publish

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --force --recursive
    - name: publish
      run: |
        cd autd-timer
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd-csv-gain
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd-holo-gain
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd-soem-link
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd-twincat-link
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd-wav-modulation
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
  