name: publish

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: publish
      run: |
        cargo test
        cargo package
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }}
