name: Publish

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --force --recursive
    - name: publish
      run: |
        cd autd3-timer
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd3-core
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd3-traits
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd3
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd3-soem-link
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd3-twincat-link
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd3-emulator-link
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
        cd autd3-holo-gain
        cargo publish --token ${{ secrets.CRATEIO_TOKEN }} || true
        cd .. && sleep 60
     