name: Publish

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --force --recursive
    - name: Publish All
      uses: ./.github/actions/cargo-publish-all
      with:
        crate-io-token: ${{ secrets.CRATEIO_TOKEN }}
